# Generated by Django 4.2.11 on 2024-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_dreams_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreams",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Select Your Gender"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
