# Generated by Django 4.2.11 on 2024-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_dreams_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreams",
            name="gender",
            field=models.CharField(
                choices=[("", ""), ("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=10,
            ),
        ),
    ]
