# Generated by Django 4.2.14 on 2024-09-18 05:44

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_dreams_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.CharField(default="", max_length=45)),
                (
                    "submission_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("email", models.EmailField(default="", max_length=200)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+10000000000", max_length=128, region=None
                    ),
                ),
                (
                    "pub",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
            ],
            options={
                "verbose_name": "dreams",
                "ordering": ["-pub"],
            },
        ),
        migrations.DeleteModel(
            name="Share",
        ),
    ]
