# Generated by Django 4.2.14 on 2024-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="desc",
            field=models.TextField(default=""),
        ),
    ]
