# Generated by Django 4.2.11 on 2026-05-27 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_contact_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreams",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional; used for collective pattern analysis.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(13),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dreams",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="dreams",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AddField(
            model_name="dreams",
            name="country_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="dreams",
            name="geo_timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dreams",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
