# Generated by Django 4.2.11 on 2026-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_dream_age_geo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "dream symbol",
                "verbose_name_plural": "dream symbols",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dreams",
            name="symbols",
            field=models.ManyToManyField(
                blank=True,
                help_text="Normalized dream imagery tags for collective pattern analysis.",
                related_name="dreams",
                to="main.dreamsymbol",
            ),
        ),
    ]
