# Generated by Django 4.2.11 on 2026-06-01 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0021_symbol_name_ci_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reply",
            new_name="DreamComment",
        ),
        migrations.RenameField(
            model_name="dreamcomment",
            old_name="reply",
            new_name="body",
        ),
        migrations.AddField(
            model_name="dreamcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dreamcomment",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="dreamcomment",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.dreams",
            ),
        ),
        migrations.AlterField(
            model_name="dreamcomment",
            name="pub",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelOptions(
            name="dreamcomment",
            options={
                "ordering": ["pub"],
                "verbose_name": "dream comment",
                "verbose_name_plural": "dream comments",
            },
        ),
    ]
