# Generated by Django 4.2.11 on 2026-06-01 11:44

from django.db import migrations, models
from django.utils import timezone


def profile_age_to_birth_year(apps, schema_editor):
    UserProfile = apps.get_model('main', 'UserProfile')
    current_year = timezone.now().year
    for profile in UserProfile.objects.exclude(age__isnull=True):
        profile.birth_year = current_year - profile.age
        profile.save(update_fields=['birth_year'])


def profile_birth_year_to_age(apps, schema_editor):
    UserProfile = apps.get_model('main', 'UserProfile')
    current_year = timezone.now().year
    for profile in UserProfile.objects.exclude(birth_year__isnull=True):
        profile.age = current_year - profile.birth_year
        profile.save(update_fields=['age'])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_profile_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Used to compute age on each new dream submission; past dreams keep their saved age.",
                null=True,
            ),
        ),
        migrations.RunPython(
            profile_age_to_birth_year,
            profile_birth_year_to_age,
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
    ]
