# Generated by Django 4.2.11 on 2026-06-01

from django.db import migrations, models


def count_existing_birth_year_as_one_use(apps, schema_editor):
    UserProfile = apps.get_model('main', 'UserProfile')
    UserProfile.objects.filter(birth_year__isnull=False).update(birth_year_updates_count=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_profile_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_year_updates_count',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Number of times birth year was saved (max 3).',
            ),
        ),
        migrations.RunPython(
            count_existing_birth_year_as_one_use,
            migrations.RunPython.noop,
        ),
    ]
