# Generated by Django 4.2.11 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_profile_birth_year_updates_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mbti_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('INTJ', 'INTJ'),
                    ('INTP', 'INTP'),
                    ('ENTJ', 'ENTJ'),
                    ('ENTP', 'ENTP'),
                    ('INFJ', 'INFJ'),
                    ('INFP', 'INFP'),
                    ('ENFJ', 'ENFJ'),
                    ('ENFP', 'ENFP'),
                    ('ISTJ', 'ISTJ'),
                    ('ISFJ', 'ISFJ'),
                    ('ESTJ', 'ESTJ'),
                    ('ESFJ', 'ESFJ'),
                    ('ISTP', 'ISTP'),
                    ('ISFP', 'ISFP'),
                    ('ESTP', 'ESTP'),
                    ('ESFP', 'ESFP'),
                ],
                default='',
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mbti_updates_count',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Number of times personality type was saved (max 3).',
            ),
        ),
    ]
