# Generated by Django 4.2.11 on 2026-06-17 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_profile_mbti_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(db_index=True, max_length=45)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "registration attempt",
                "verbose_name_plural": "registration attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
